import firebaseui from "firebaseui";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import { Footer } from "../components/Footer";
import {
  BeakerIcon,
  CalendarIcon,
  ExternalLinkIcon,
  LocationMarkerIcon,
  UserGroupIcon,
} from "@heroicons/react/outline";
import { Button } from "../components/Button";
import { getAuth } from "@firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { Header } from "../components/Header";
import { ClassTimetable } from "../components/ClassTimetable";

const Home: NextPage = () => {
  const [user, loading, error] = useAuthState(getAuth());
  return (
    <div className="">
      <Head>
        <title>Salsa Therapy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-inter antialiased bg-gray-100 text-gray-600">
        <Header />

        <div className="flex flex-col min-h-full justify-between">
          <main className="flex gap-8 px-8 py-10">
            <ClassTimetable />

            <div className="shadow-xl border border-gray-300 bg-white flex-1 rounded-md self-start">
              <h2 className="p-4 font-bold border-b text-2xl">Tone</h2>
              <div className="p-4 border-b">
                <div className="flex gap-2 items-center">
                  <CalendarIcon className="h-4 w-4" />
                  Thursday, 11 November 2021 7:30am – 8:15am NZDT
                </div>
                <div className="flex gap-2 items-center">
                  <LocationMarkerIcon className="h-4 w-4" />
                  <a
                    href="https://g.page/SalsaTherapy?share"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:underline hover:text-purple-500 flex items-center"
                  >
                    Full Swing, 80 Cuba Street, Te Aro, Wellington 6011
                    <ExternalLinkIcon className="h-4 w-4 inline-block ml-1" />
                  </a>
                </div>
                <div className="flex gap-2 items-center">
                  <UserGroupIcon className="h-4 w-4" />6 spaces available
                </div>
              </div>
              <div className="p-4 border-b">
                <h3 className="text-lg font-bold">Details</h3>
                <p>
                  Fun and sweaty class, really focusing on technique and getting
                  the most out of our exercises. We'll be toning our muscles we
                  use most for dancing while grooving to upbeat music!
                </p>
              </div>
              <div className="p-4 border-b">
                <h3 className="text-lg font-bold">Instructions</h3>
                <p>
                  Bring comfy workout clothes, good gym shoes. Bring a mat for
                  floor work but not mandatory.
                </p>
              </div>
              <div className="p-4">
                <h3 className="text-lg font-bold">Tickets</h3>
                <div className="flex justify-between items-end">
                  <div className="text-lg">$15.00</div>
                  <Button>Book class</Button>
                </div>
              </div>
            </div>
          </main>
        </div>

        <Footer />
      </div>
    </div>
  );
};

export default Home;
